server:
  port: @server.port@

management:
  security:
    flag: false
  metrics:
    export:
      statsd:
        enabled: false
        flavor: etsy
  endpoint.health.show-details: always

spring:
  application:
    name: @project.name@
  output:
    ansi:
      enabled: always
info:
  version: @project.version@
  stage: dev

clickhouse.db:
  url: "jdbc:clickhouse://localhost:8123/default"
  user: "user"
  password: "password"
  connection.timeout: 50000
  compress: false

kafka:
  bootstrap.servers: localhost:9092
  max:
    retry.attempts: 3
    poll.records: 100
  topic:
    event.sink:
      initial: event_sink
      aggregated: aggregated_event_sink
      aggregatedRefund: aggregated_event_sink_refund
  consumer:
      prefix: analytics
      concurrency: 7
      throttling-timeout-ms: 1000
  ssl:
    enabled: false
  state:
    dir: tmp/state-store/
  block.cache.size: 10

service:
  invoicing:
    url: http://hellgate:8022/v1/processing/invoicing
    networkTimeout: 5000